export const WILAYAS = [
  { id: 1, name: "Adrar", nameAr: "أدرار" },
  { id: 2, name: "Chlef", nameAr: "الشلف" },
  { id: 3, name: "Laghouat", nameAr: "الأغواط" },
  { id: 4, name: "Oum El Bouaghi", nameAr: "أم البواقي" },
  { id: 5, name: "Batna", nameAr: "باتنة" },
  { id: 6, name: "Béjaïa", nameAr: "بجاية" },
  { id: 7, name: "Biskra", nameAr: "بسكرة" },
  { id: 8, name: "Béchar", nameAr: "بشار" },
  { id: 9, name: "Blida", nameAr: "البليدة" },
  { id: 10, name: "Bouira", nameAr: "البويرة" },
  { id: 11, name: "Tamanrasset", nameAr: "تمنراست" },
  { id: 12, name: "Tébessa", nameAr: "تبسة" },
  { id: 13, name: "Tlemcen", nameAr: "تلمسان" },
  { id: 14, name: "Tiaret", nameAr: "تيارت" },
  { id: 15, name: "Tizi Ouzou", nameAr: "تيزي وزو" },
  { id: 16, name: "Alger", nameAr: "الجزائر" },
  { id: 17, name: "Djelfa", nameAr: "الجلفة" },
  { id: 18, name: "Jijel", nameAr: "جيجل" },
  { id: 19, name: "Sétif", nameAr: "سطيف" },
  { id: 20, name: "Saïda", nameAr: "سعيدة" },
  { id: 21, name: "Skikda", nameAr: "سكيكدة" },
  { id: 22, name: "Sidi Bel Abbès", nameAr: "سيدي بلعباس" },
  { id: 23, name: "Annaba", nameAr: "عنابة" },
  { id: 24, name: "Guelma", nameAr: "قالمة" },
  { id: 25, name: "Constantine", nameAr: "قسنطينة" },
  { id: 26, name: "Médéa", nameAr: "المدية" },
  { id: 27, name: "Mostaganem", nameAr: "مستغانم" },
  { id: 28, name: "M'Sila", nameAr: "المسيلة" },
  { id: 29, name: "Mascara", nameAr: "معسكر" },
  { id: 30, name: "Ouargla", nameAr: "ورقلة" },
  { id: 31, name: "Oran", nameAr: "وهران" },
  { id: 32, name: "El Bayadh", nameAr: "البيض" },
  { id: 33, name: "Illizi", nameAr: "إليزي" },
  { id: 34, name: "Bordj Bou Arréridj", nameAr: "برج بوعريريج" },
  { id: 35, name: "Boumerdès", nameAr: "بومرداس" },
  { id: 36, name: "El Tarf", nameAr: "الطارف" },
  { id: 37, name: "Tindouf", nameAr: "تندوف" },
  { id: 38, name: "Tissemsilt", nameAr: "تيسمسيلت" },
  { id: 39, name: "El Oued", nameAr: "الوادي" },
  { id: 40, name: "Khenchela", nameAr: "خنشلة" },
  { id: 41, name: "Souk Ahras", nameAr: "سوق أهراس" },
  { id: 42, name: "Tipaza", nameAr: "تيبازة" },
  { id: 43, name: "Mila", nameAr: "ميلة" },
  { id: 44, name: "Aïn Defla", nameAr: "عين الدفلى" },
  { id: 45, name: "Naâma", nameAr: "النعامة" },
  { id: 46, name: "Aïn Témouchent", nameAr: "عين تموشنت" },
  { id: 47, name: "Ghardaïa", nameAr: "غرداية" },
  { id: 48, name: "Relizane", nameAr: "غليزان" },
  { id: 49, name: "Timimoun", nameAr: "تيميمون" },
  { id: 50, name: "Bordj Badji Mokhtar", nameAr: "برج باجي مختار" },
  { id: 51, name: "Ouled Djellal", nameAr: "أولاد جلال" },
  { id: 52, name: "Béni Abbès", nameAr: "بني عباس" },
  { id: 53, name: "In Salah", nameAr: "عين صالح" },
  { id: 54, name: "In Guezzam", nameAr: "عين قزام" },
  { id: 55, name: "Touggourt", nameAr: "تقرت" },
  { id: 56, name: "Djanet", nameAr: "جانت" },
  { id: 57, name: "El M'Ghair", nameAr: "المغير" },
  { id: 58, name: "El Meniaa", nameAr: "المنيعة" },
];

/**
 * Communes (baladias) grouped by wilaya ID.
 * This is a representative subset — expand as needed.
 */
export const COMMUNES_BY_WILAYA: Record<number, string[]> = {
  1: ["Adrar", "Aoulef", "Reggane", "Timimoun", "Zaouiet Kounta"],
  2: ["Chlef", "Ténès", "Boukadir", "El Karimia", "Oued Fodda"],
  3: ["Laghouat", "Aflou", "Brida", "Hassi R'Mel", "Ksar El Hirane"],
  4: ["Oum El Bouaghi", "Aïn Beïda", "Aïn M'Lila", "Meskiana", "Sigus"],
  5: ["Batna", "Aïn Touta", "Arris", "Barika", "Biskra", "Chemora", "El Madher", "Ichmoul", "Merouana", "N'Gaous", "Ouled Si Slimane", "Ras El Aioun", "Seriana", "Tazoult", "Timgad"],
  6: ["Béjaïa", "Akbou", "Aokas", "Amizour", "El Kseur", "Kherrata", "Sidi Aïch", "Tazmalt", "Tichy"],
  7: ["Biskra", "Ouled Djellal", "Sidi Okba", "Tolga", "Zribet El Oued", "El Kantara"],
  8: ["Béchar", "Abadla", "Beni Abbès", "Kenadsa", "Taghit"],
  9: ["Blida", "Bougara", "Chréa", "Larbaa", "Meftah", "Ouled Yaïch"],
  10: ["Bouira", "Aïn Bessem", "Aïn El Hadjar", "Aomar", "Lakhdaria", "M'Chedallah", "Sour El Ghouzlane"],
  11: ["Tamanrasset", "Abalessa", "Idles", "In Ghar", "In Guezzam", "Tin Zaouatine"],
  12: ["Tébessa", "Aïn Zerga", "Bir El Ater", "Cheria", "El Aouinet", "Negrine"],
  13: ["Tlemcen", "Aïn Temouchent", "Ghazaouet", "Maghnia", "Nedroma", "Remchi", "Sebdou"],
  14: ["Tiaret", "Frenda", "Ksar Chellala", "Mahdia", "Mechraa Sfa", "Sougueur"],
  15: ["Tizi Ouzou", "Azazga", "Aïn El Hammam", "Boghni", "Draa Ben Khedda", "Maatkas", "Tigzirt"],
  16: ["Alger Centre", "Bab El Oued", "Birkhadem", "Bir Mourad Raïs", "Bouzaréah", "Cheraga", "Dar El Beïda", "Draria", "El Biar", "El Harrach", "Hussein Dey", "Kouba", "Rouiba", "Sidi M'Hamed"],
  17: ["Djelfa", "Aïn Oussera", "Birine", "Dar Chioukh", "El Idrissia", "Messaad"],
  18: ["Jijel", "El Aouana", "El Milia", "Taher", "Ziama Mansouriah"],
  19: ["Sétif", "Aïn Azel", "Aïn El Kebira", "Bougaa", "El Eulma", "Guenzet", "Maoklane"],
  20: ["Saïda", "Aïn El Hadjar", "Aïn Soltane", "El Hassasna", "Sidi Ahmed"],
  21: ["Skikda", "Azzaba", "Collo", "El Harrouch", "Ramdane Djamel", "Tamalous"],
  22: ["Sidi Bel Abbès", "Aïn Thrid", "Ben Badis", "Marhoum", "Ras El Ma", "Tessala"],
  23: ["Annaba", "Berrahal", "Bouteldja", "El Hadjar", "El Tarf", "Seraïdi"],
  24: ["Guelma", "Aïn Makhlouf", "Bouchegouf", "Hammam Debagh", "Héliopolis"],
  25: ["Constantine", "Aïn Abid", "El Khroub", "Hamma Bouziane", "Ibn Ziad", "Zighoud Youcef"],
  26: ["Médéa", "Aïn Boucif", "Berrouaghia", "Ksar El Boukhari", "Ouled Antar", "Tablat"],
  27: ["Mostaganem", "Aïn Tedles", "Hassi Mameche", "Mazaghran", "Stidia"],
  28: ["M'Sila", "Aïn El Hadjel", "Bou Saada", "Magra", "Sidi Aïssa"],
  29: ["Mascara", "Aïn Farès", "Ghriss", "Hachem", "Mohammadia", "Sig", "Tighennif"],
  30: ["Ouargla", "El Borma", "Ghardaïa", "Hassi Messaoud", "Rouissat", "Touggourt"],
  31: ["Oran", "Aïn El Turck", "Bir El Djir", "Es Senia", "Gdyel", "Mers El Kebir", "Oued Tlélat"],
  32: ["El Bayadh", "Brezina", "El Abiodh Sidi Cheikh", "Rogassa", "Stitten"],
  33: ["Illizi", "Bordj Omar Driss", "Djanet", "In Amenas"],
  34: ["Bordj Bou Arréridj", "Aïn Taghrout", "El Achir", "El Hamadia", "Ras El Oued"],
  35: ["Boumerdès", "Boudouaou", "Dellys", "Khemis El Khechna", "Naciria", "Thénia"],
  36: ["El Tarf", "Aïn El Assel", "Ben Mehidi", "Besbes", "Bouteldja", "Drean"],
  37: ["Tindouf"],
  38: ["Tissemsilt", "Bordj Bou Naama", "Khemisti", "Lardjem", "Theniet El Had"],
  39: ["El Oued", "Bayadha", "Débila", "Guemar", "Reguiba", "Still"],
  40: ["Khenchela", "Aïn Touila", "Babar", "Chechar", "Kais", "Ouled Rechache"],
  41: ["Souk Ahras", "Aïn Zana", "Dréa", "Mechroha", "Merahna", "Sedrata"],
  42: ["Tipaza", "Aïn Tagourait", "Bou Ismaïl", "Cherchell", "Koléa", "Mselmia"],
  43: ["Mila", "Aïn Beïda Illich", "Chelghoum Laïd", "Ferdjioua", "Sidi Merouane", "Tassadane Haddada"],
  44: ["Aïn Defla", "Aïn Lahdjar", "Bir Ould Khelifa", "El Abadia", "Khemis Miliana", "Miliana"],
  45: ["Naâma", "Aïn Sefra", "Mécheria", "Moghrar", "Sfissifa"],
  46: ["Aïn Témouchent", "Aïn El Arba", "Beni Saf", "Hammam Bou Hadjar", "Oulhaça El Gheraba"],
  47: ["Ghardaïa", "Berriane", "El Guerrara", "Metlili", "Zelfana"],
  48: ["Relizane", "Aïn Tarek", "Mazouna", "Oued Rhiou", "Zemmoura"],
  49: ["Timimoun", "Aougrout", "Charouine", "Ouled Saïd"],
  50: ["Bordj Badji Mokhtar", "Timiaouine"],
  51: ["Ouled Djellal", "Dhaïet Ben Dhaoua", "Sidi Khaled"],
  52: ["Béni Abbès", "Beni Ikhlef", "El Ouata", "Ouled Khoudir"],
  53: ["In Salah", "Foggaret Ezzaouia", "In Ghar"],
  54: ["In Guezzam", "Tin Zaouatine"],
  55: ["Touggourt", "Megarine", "Nezla", "Temacine", "Taibet"],
  56: ["Djanet", "Bordj El Haouasse"],
  57: ["El M'Ghair", "Djamaa", "Reguiba", "Sidi Amrane"],
  58: ["El Meniaa", "Hassi Gara"],
};
